### ISSUE TITLE
Missing dependency 

### ISSUE THREAD

**Issue by LenReinhart** [adafruit/circup#104]
Using the RP2040 Feather with the APDS9960 the following error came up after loading the color example:
File "code.py", line 7, in <module>
  File "adafruit_apds9960/apds9960.py", line 16, in <module>
ImportError: no module named 'adafruit_register'

**Comment by askpatrickw** [comment]
This is because the  Adafruit_CircuitPython_APDS9960 does not have adafruit_register. In its requirements.txt
https://github.com/adafruit/Adafruit_CircuitPython_APDS9960/blob/master/requirements.txt

Can you open an issue in that repo and do a PR to fix?

**Comment by askpatrickw** [comment]
hmm... looking at this more closely. I see it in requirements.txt.

**Comment by askpatrickw** [comment]
My test:

```
circup install adafruit_apds9960

Found device at /Volumes/CIRCUITPY, running CircuitPython 6.2.0-beta.3-104-g7c610bdd2-dirty.
A newer version of CircuitPython (6.2.0) is available.
Searching for dependencies for: ['adafruit_apds9960']
Ready to install: ['adafruit_apds9960', 'adafruit_bus_device', 'adafruit_register']

Installed 'adafruit_apds9960'.
'adafruit_bus_device' is already installed.
Installed 'adafruit_register'.
```

@LenReinhart  Can you check your version of circup for me by running circup --version. It should be 0.9.4

**Comment by LenReinhart** [comment]
Where do I do this? I tried from >>> connected to the RP2040 and got:

 

Press any key to enter the REPL. Use CTRL-D to reload.

 

Adafruit CircuitPython 6.2.0 on 2021-04-05; Adafruit Feather RP2040 with rp2040

>>> circup --version

Traceback (most recent call last):

File "<stdin>", line 1, in <module>

NameError: name 'circup' is not defined

**Comment by askpatrickw** [comment]
@LenReinhart  [Circup is a command-line too](https://github.com/adafruit/circup/blob/master/README.rst)l run from your desktop\laptop to install CircuitPython libraries onto your device. 

Are you sure you're using Circup?

**Comment by LenReinhart** [comment]
I thought Circup was adafruit shorthand for Circuit Python, I looked it up on the Adafruit site and have installed it. My device now says Adafruit Register is installed and I will proceed from here. Assume problem solved. Thanks, without your involvement I would have not known about Circup.

**Comment by askpatrickw** [comment]
No worries @LenReinhart. Happy to help.  There is a great community on Discord and a #help-with-circuitpython channel you might find useful.  https://adafru.it/discord
