### ISSUE TITLE
Several Libraries have dependencies which fail to install

### ISSUE THREAD

**Issue by askpatrickw** [adafruit/circup#122]
None or some of these may be a circup issue. Just capturing this while I look into it.

- [x]     {'adafruit_pyoa': 'adafruit_display_button'}, -- this is using a non standard naming, needs to be special cased - https://github.com/adafruit/circup/pull/123
- [x]     {'arrowline': 'vectorio'}, -- vectorio is in CP and does not need to be in requirements. https://github.com/jposada202020/CircuitPython_ArrowLine/pull/4
- [x]     {'jepler_udecimal': 'astroid'},  -- there are many things in the requirments (black, sphinx, etc..) https://github.com/jepler/Jepler_CircuitPython_udecimal/issues/5

**Comment by FoamyGuy** [comment]
I'm not sure about the others, but `vectorio` is a built-in module it doesn't need to be installed with circup, it's included in the core of builds that can use it.

**Comment by Neradoc** [comment]
`adafruit_button` is one of those Adafruit libraries that have a non regular name and should likely be added to the `not_standard_names` list like `adafruit_sd` and the others.
```py
        "adafruit_display_button": "adafruit_button",
```

**Comment by askpatrickw** [comment]
> I'm not sure about the others, but `vectorio` is a built-in module it doesn't need to be installed with circup, it's included in the core of builds that can use it.

@FoamyGuy  But if you're using the library with Blinka, you will need to `pip install vectorio`.

**Comment by FoamyGuy** [comment]
> > I'm not sure about the others, but `vectorio` is a built-in module it doesn't need to be installed with circup, it's included in the core of builds that can use it.
> 
> @FoamyGuy But if you're using the library with Blinka, you will need to `pip install vectorio`.

@askpatrickw  As far as I know there is no CPython / Blinka implementation of `vectorio`. There is this PyPi entry, but I believe it's unrelated to circuitpython: https://pypi.org/project/vectorio/

If it did exist I think it would be inside of https://github.com/adafruit/Adafruit_Blinka_Displayio rather than it's own library, but am not certain of that.

**Comment by askpatrickw** [comment]
Thanks @FoamyGuy, I just assumed they were the same. We should have Arrowline change. I'll follow-up.

**Comment by askpatrickw** [comment]
All the affected libraries are updated
