### ISSUE TITLE
Unable to handle utf-8 encoding for asyncio

### ISSUE THREAD

**Issue by manugupt1** [adafruit/circup#139]
- Platform/operating system (i.e. Raspberry Pi with Raspbian operating system,
  Windows 32-bit, Windows 64-bit, Mac OSX 64-bit, etc.):  MacOSX Monterey

- Python version (run `python -version` or `python3 -version`):  Python 3.8.8

- Error message you are receiving, including any Python exception traces:  **INSERT
  ERROR MESAGE/EXCEPTION TRACES HERE***

```
12/28/2021 16:56:53 INFO: version is b'io/__init__.py\x80\rJH"\'&\'\'&\'&&&i`\x00\x81\x10\x00\x05*\x01\x1b\x08corei\x83\x80\x80*\x03'
12/28/2021 16:56:53 ERROR: 'utf-8' codec can't decode byte 0x80 in position 14: invalid start byte
Traceback (most recent call last):
  File "/Users/manu/opt/anaconda3/lib/python3.8/site-packages/circup/__init__.py", line 641, in find_modules
    device_modules = get_device_versions(device_path)
  File "/Users/manu/opt/anaconda3/lib/python3.8/site-packages/circup/__init__.py", line 904, in get_device_versions
    return get_modules(os.path.join(device_path, "lib"))
  File "/Users/manu/opt/anaconda3/lib/python3.8/site-packages/circup/__init__.py", line 955, in get_modules
    metadata = extract_metadata(source)
  File "/Users/manu/opt/anaconda3/lib/python3.8/site-packages/circup/__init__.py", line 551, in extract_metadata
    result = {"__version__": version.decode("utf-8"), "mpy": True}
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 14: invalid start byte
```

- List the steps to reproduce the problem below (if possible attach code or commands
  to run): **LIST REPRO STEPS BELOW**

I downloaded the latest bundle and it was not able to parse the version info from it. I have added the module that it failed on by getting the stack trace.

[asyncio.zip](https://github.com/adafruit/circup/files/7786900/asyncio.zip)

**Comment by Neradoc** [comment]
Ah that might be the library having a `__version__` that does not follow circup's expectations, it's a tuple, not the auto-generated string Circuitpython libraries use. Circup should probably print and log an error, and default to no version information. (Also submitted a fix for asyncio).
