### ISSUE TITLE
Suppress warning about circuitpython_typing

### ISSUE THREAD

**Issue by dhalbert** [adafruit/circup#141]
Now that `circuitpython_typing is a separate library, but is not in the bundle (because it's typing definitions only), we are seeing a warning:

```py
$ circup install adafruit_bus_device
Found device at /media/halbert/CIRCUITPY, running CircuitPython 7.2.0-alpha.1-276-g8d4333203.
Searching for dependencies for: ['adafruit_bus_device']
WARNING:
	adafruit_typing is not a known CircuitPython library.
Ready to install: ['adafruit_bus_device']
```
Suppress this warning.

**Comment by askpatrickw** [comment]
I think the fix is to add `adafruit_typing` to the list of libraries not intended to be installed on a board.

https://github.com/adafruit/circup/blob/main/circup/__init__.py#L49

**Comment by dhalbert** [comment]
The other bug here is that it's not `adafruit_typing`, it's `circuitpython_typing`, and the pypi name is `adafruit-circuitpython-typing`. I'll fix the appropriate libraries.
