### ISSUE TITLE
can't install 1.2.3

### ISSUE THREAD

**Issue by dsssssssss9** [adafruit/circup#169]
- Platform/operating system : Ubuntu 20.04

- Python version : Python 3.8.10

- Error message you are receiving, : Requirement already satisfied: circup in ./.local/lib/python3.8/site-packages (1.2.2)

- List the steps to reproduce the problem below

pip3 install circup

Or 

pip3 install -upgrade circup 

These commands have always worked before with no problems

even though 1.2.3has been released every time i try to install it i get the above error

Even happens if i specify the version to install with...
python3 -m pip install "circup==1.2.3"

Any help appreciated

**Comment by dhalbert** [comment]
I would expect `pip3 install -upgrade circup` to upgrade. I just tried it myself on Ubuntu 22.04, and it worked. But you are on an older version. The change between 1.2.2 and 1.2.3 was to upgrade `requests`, which says it still supports 3.7 and up. If this still doesn't work for you, what does `pip3 list` show? I'll compare it with what I have, and let's compare it with https://github.com/adafruit/circup/blob/main/requirements.txt.

**Comment by dsssssssss9** [comment]
Hi

Thanks for getting back to me so quickly ...

here are my results ....

`pip3 list
Package                                 Version
--------------------------------------- --------------------
Adafruit-Blinka                         6.15.0
adafruit-board-toolkit                  1.1.0
adafruit-circuitpython-busdevice        5.1.1
adafruit-circuitpython-displayio-sh1106 1.2.3
adafruit-circuitpython-max7219          1.4.1
adafruit-circuitpython-us100            1.1.5
Adafruit-GPIO                           1.0.3
adafruit-nrfutil                        0.5.3.post16
Adafruit-PlatformDetect                 3.16.0
Adafruit-PureIO                         1.1.8
Adafruit-SSD1306                        1.6.2
appdirs                                 1.4.3
apturl                                  0.5.2
argcomplete                             1.12.3
astroid                                 2.5.2
asttokens                               2.0.4
backcall                                0.2.0
bcrypt                                  3.1.7
black                                   20.8b1
blinker                                 1.4
Brlapi                                  0.7.0
cajarename                              19.7.15
certifi                                 2019.11.28
cffi                                    1.15.0
chardet                                 3.0.4
circup                                  1.2.2
click                                   8.0.3
colorama                                0.4.3
colorzero                               1.1
command-not-found                       0.3
configobj                               5.0.6
cryptography                            35.0.0
cupshelpers                             1.0
cycler                                  0.10.0
dbus-python                             1.2.16
decorator                               4.4.2
defer                                   1.0.6
deja-dup-caja                           0.0.6
distlib                                 0.3.0
distro                                  1.4.0
distro-info                             0.23ubuntu1
dnspython                               1.16.0
docutils                                0.16
duplicity                               0.8.12.0
ecdsa                                   0.17.0
entrypoints                             0.3
fasteners                               0.14.1
filelock                                3.0.12
findimports                             2.1.0
flake8                                  3.9.0
folder-color-caja                       0.0.86
folder-color-common                     0.0.86
future                                  0.18.2
gpg                                     1.13.1-unknown
gpiozero                                1.5.1
grove.py                                0.6
guizero                                 1.1.1
httplib2                                0.14.0
idna                                    2.8
importlib-metadata                      1.5.0
intelhex                                2.3.0
intervaltree                            3.1.0
ipykernel                               5.5.0
ipython                                 7.21.0
ipython-genutils                        0.2.0
isort                                   5.8.0
jedi                                    0.18.1
jupyter-client                          6.1.12
jupyter-core                            4.7.1
kazam                                   1.5.3
keyring                                 18.0.1
keyrings.alt                            3.4.0
kiwisolver                              1.3.1
language-selector                       0.1
launchpadlib                            1.10.13
lazr.restfulclient                      0.14.2
lazr.uri                                1.0.3
lazy-object-proxy                       1.6.0
lockfile                                0.12.2
louis                                   3.12.0
lxml                                    4.5.0
Mako                                    1.1.0
Markdown                                3.1.1
MarkupSafe                              1.1.0
mate-hud                                19.10.0
mate-menu                               20.4.1
mate-tweak                              20.4.0
matplotlib                              2.2.2
mccabe                                  0.6.1
micropython-cpython-framebuf            0.0
monotonic                               1.5
more-itertools                          4.2.0
mypy                                    0.812
mypy-extensions                         0.4.3
netifaces                               0.10.4
nudatus                                 0.0.5
numpy                                   1.17.4
oauthlib                                3.1.0
olefile                                 0.46
packaging                               20.3
paramiko                                2.6.0
parso                                   0.8.1
pathspec                                0.8.1
pexpect                                 4.6.0
pgzero                                  1.2
pickleshare                             0.7.5
pigpio                                  1.78
Pillow                                  7.0.0
pip                                     23.1.2
pipx                                    1.2.0
platformdirs                            2.4.0
polib                                   1.1.0
prompt-toolkit                          3.0.17
psutil                                  5.5.1
pulsemixer                              1.5.0
pycairo                                 1.16.2
pycodestyle                             2.7.0
pycparser                               2.21
pycrypto                                2.6.1
pycups                                  1.9.73
pycurl                                  7.43.0.2
pyelftools                              0.27
pyflakes                                2.3.0
pyftdi                                  0.53.3
pygame                                  1.9.6
Pygments                                2.3.1
PyGObject                               3.36.0
PyJWT                                   1.7.1
pylint                                  2.7.4
PyNaCl                                  1.3.0
pyocd                                   0.19.0
pyOpenSSL                               21.0.0
pyparsing                               2.4.6
PyQt5                                   5.13.2
PyQt5-sip                               12.8.1
PyQtChart                               5.13.1
pyserial                                3.5
python-apt                              2.0.1+ubuntu0.20.4.1
python-dateutil                         2.7.3
python-debian                           0.1.36ubuntu1
python-xapp                             1.8.1
python-xlib                             0.23
pytz                                    2021.1
pyusb                                   1.2.1
pyxdg                                   0.26
PyYAML                                  5.3.1
pyzmq                                   22.0.3
QScintilla                              2.11.3
qtconsole                               4.7.7
QtPy                                    1.9.0
regex                                   2021.3.17
reportlab                               3.5.34
requests                                2.22.0
requests-unixsocket                     0.2.0
scipy                                   1.3.3
SecretStorage                           2.3.1
semver                                  2.13.0
Send2Trash                              1.5.0
setproctitle                            1.1.10
setuptools                              45.2.0
shortcut                                0.0.2
simplejson                              3.16.0
sip                                     4.19.21
six                                     1.14.0
smbus                                   1.1.post2
smbus2                                  0.4.1
sortedcontainers                        2.4.0
spidev                                  3.5
systemd-python                          234
thonny                                  4.0.2
toml                                    0.10.2
tomli                                   1.2.3
tornado                                 6.1
traitlets                               5.0.5
typed-ast                               1.4.2
typing-extensions                       3.7.4.3
ubittool                                0.5.0
ubuntu-advantage-tools                  8001
ubuntu-drivers-common                   0.0.0
uflash                                  1.2.0
ufw                                     0.36
unattended-upgrades                     0.1
update-checker                          0.18.0
urllib3                                 1.25.8
usb-creator                             0.3.7
userpath                                1.7.0
virtualenv                              20.0.17
wadllib                                 1.3.3
wcwidth                                 0.2.5
websocket-client                        1.2.1
websockets                              10.0
wheel                                   0.34.2
wrapt                                   1.12.1
xkit                                    0.0.0
zipp                                    1.0.0
`

**Comment by dhalbert** [comment]
It appears to me `circup`'s `requirements.txt` is not being used at all. Both my packages and yours are behind the list, though yours are further behind than mine.

I am not sure why they are all pinned like that. That unnecessarily limits other packages.

Here are some instructions for updating packages: https://www.activestate.com/resources/quick-reads/how-to-update-all-python-packages/. Scroll down to "Update all Python Packages on Linux".

@Neradoc @tekktrik I am not that familiar with the packaging requirements issues here. Do you have a comment? Thanks.

**Comment by dsssssssss9** [comment]
I have tried both sets of instructions on the site you kindly linked 

took ages & several errors scrolled by that unfortunate i did not record them

i have tried 
`pip3 uninstall  circup
Found existing installation: circup 1.2.2
Uninstalling circup-1.2.2:
  Would remove:
    /home/jkd/.local/bin/circup
    /home/jkd/.local/lib/python3.8/site-packages/circup-1.2.2.dist-info/*
    /home/jkd/.local/lib/python3.8/site-packages/circup/*
Proceed (Y/n)? Y
  Successfully uninstalled circup-1.2.2
jkd@jkd-mininuc:~$ circup
circup: command not found
`
followed  by

`python3 -m pip install "circup==1.2.3"
Defaulting to user installation because normal site-packages is not writeable
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple/
ERROR: Could not find a version that satisfies the requirement circup==1.2.3 (from versions: 0.0.1, 0.0.3, 0.0.4, 0.0.5, 0.0.6, 0.0.8, 0.1.0, 0.2.2, 0.3.1, 0.4.0, 0.4.1, 0.5.0, 0.6.0, 0.6.1, 0.7.0, 0.8.0, 0.9.0, 0.9.1, 0.9.2, 0.9.3, 0.9.4, 0.9.5, 0.9.7, 0.9.8, 0.9.9, 0.9.10, 0.9.11, 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.1.0, 1.1.1, 1.1.2, 1.1.3, 1.1.4, 1.1.5, 1.2.0, 1.2.1, 1.2.2)
ERROR: No matching distribution found for circup==1.2.3
` 


so have installed 1.2.2 again for now 
Hope we can get to the bottom of this?

**Comment by tekktrik** [comment]
I can take a look in a couple days, or hopefully tonight if I have a free moment!

**Comment by dsssssssss9** [comment]
Latest results after doing the above....

`pip3 list
Package                                 Version
--------------------------------------- --------------------
Adafruit-Blinka                         8.19.0
adafruit-board-toolkit                  1.1.1
adafruit-circuitpython-busdevice        5.2.4
adafruit-circuitpython-displayio-sh1106 1.2.10
adafruit-circuitpython-framebuf         1.6.1
adafruit-circuitpython-max7219          1.5.9
adafruit-circuitpython-requests         1.13.2
adafruit-circuitpython-typing           1.9.2
adafruit-circuitpython-us100            1.1.13
Adafruit-GPIO                           1.0.3
adafruit-nrfutil                        0.5.3.post16
Adafruit-PlatformDetect                 3.45.2
Adafruit-PureIO                         1.1.10
Adafruit-SSD1306                        1.6.2
appdirs                                 1.4.4
apturl                                  0.5.2
argcomplete                             3.0.8
astroid                                 2.15.4
asttokens                               2.2.1
backcall                                0.2.0
bcrypt                                  4.0.1
black                                   23.3.0
blinker                                 1.6.2
Brlapi                                  0.7.0
cajarename                              19.7.15
capstone                                4.0.2
certifi                                 2023.5.7
cffi                                    1.15.1
chardet                                 5.1.0
charset-normalizer                      3.1.0
circup                                  1.2.2
click                                   8.1.3
cmsis-pack-manager                      0.5.2
colorama                                0.4.6
colorzero                               2.0
comm                                    0.1.3
command-not-found                       0.3
configobj                               5.0.8
contourpy                               1.0.7
cryptography                            40.0.2
cupshelpers                             1.0
cycler                                  0.11.0
dbus-python                             1.2.16
debugpy                                 1.6.7
decorator                               5.1.1
defer                                   1.0.6
deja-dup-caja                           0.0.6
dill                                    0.3.6
distlib                                 0.3.6
distro                                  1.8.0
distro-info                             1.0
dnspython                               2.3.0
docutils                                0.20
duplicity                               0.8.12.0
ecdsa                                   0.18.0
entrypoints                             0.4
executing                               1.2.0
fasteners                               0.18
filelock                                3.12.0
findimports                             2.3.0
flake8                                  6.0.0
folder-color-caja                       0.0.86
folder-color-common                     0.0.86
fonttools                               4.39.4
future                                  0.18.3
gpg                                     1.13.1-unknown
gpiozero                                1.6.2
grove.py                                0.6
guizero                                 1.4.0
httplib2                                0.22.0
idna                                    3.4
importlib-metadata                      6.6.0
importlib-resources                     5.12.0
intelhex                                2.3.0
intervaltree                            3.1.0
ipykernel                               6.23.0
ipython                                 8.12.2
ipython-genutils                        0.2.0
isort                                   5.12.0
jaraco.classes                          3.2.3
jedi                                    0.18.2
jeepney                                 0.8.0
jupyter_client                          8.2.0
jupyter_core                            5.3.0
kazam                                   1.5.6
keyring                                 23.13.1
keyrings.alt                            4.2.0
kiwisolver                              1.4.4
language-selector                       0.1
lark                                    1.1.5
latest                                  0.6.0
launchpadlib                            1.11.0
lazr.restfulclient                      0.14.5
lazr.uri                                1.0.6
lazy-object-proxy                       1.9.0
libusb-package                          1.0.26.1
lockfile                                0.12.2
louis                                   3.12.0
lxml                                    4.9.2
Mako                                    1.2.4
Markdown                                3.4.3
MarkupSafe                              2.1.2
mate-hud                                19.10.0
mate-menu                               20.4.1
mate-tweak                              20.4.0
matplotlib                              3.7.1
matplotlib-inline                       0.1.6
mccabe                                  0.7.0
micropython-cpython-framebuf            0.0
monotonic                               1.6
more-itertools                          9.1.0
mypy                                    1.3.0
mypy-extensions                         1.0.0
natsort                                 8.3.1
nest-asyncio                            1.5.6
netifaces                               0.11.0
nudatus                                 0.0.5
numpy                                   1.24.3
oauthlib                                3.2.2
olefile                                 0.46
packaging                               23.1
paramiko                                3.1.0
parso                                   0.8.3
pathspec                                0.11.1
pexpect                                 4.8.0
pgzero                                  1.2.1
pickleshare                             0.7.5
pigpio                                  1.78
Pillow                                  9.5.0
pip                                     23.1.2
pipx                                    1.2.0
platformdirs                            3.5.1
ply                                     3.11
polib                                   1.2.0
prettytable                             3.7.0
prompt-toolkit                          3.0.38
psutil                                  5.9.5
ptyprocess                              0.7.0
pulsemixer                              1.5.1
pure-eval                               0.2.2
pycairo                                 1.16.2
pycodestyle                             2.10.0
pycparser                               2.21
pycrypto                                2.6.1
pycups                                  1.9.73
pycurl                                  7.43.0.2
pyelftools                              0.29
pyflakes                                3.0.1
pyftdi                                  0.54.0
pygame                                  2.4.0
Pygments                                2.15.1
PyGObject                               3.36.0
PyJWT                                   2.7.0
pylink-square                           1.1.0
pylint                                  2.17.4
PyNaCl                                  1.5.0
pyocd                                   0.35.0
pyOpenSSL                               23.1.1
pyparsing                               3.0.9
PyQt5                                   5.15.9
PyQt5-Qt5                               5.15.2
PyQt5-sip                               12.12.1
PyQtChart                               5.15.6
PyQtChart-Qt5                           5.15.2
pyserial                                3.5
python-apt                              2.0.1+ubuntu0.20.4.1
python-dateutil                         2.8.2
python-debian                           0.1.49
python-xapp                             1.8.1
python-xlib                             0.33
pytz                                    2023.3
pyusb                                   1.2.1
pyxdg                                   0.28
PyYAML                                  6.0
pyzmq                                   25.0.2
QScintilla                              2.14.0
qtconsole                               5.4.3
QtPy                                    2.3.1
regex                                   2023.5.5
reportlab                               3.5.34
requests                                2.30.0
requests-unixsocket                     0.3.0
scipy                                   1.10.1
sdist                                   0.0.0
SecretStorage                           3.3.3
semver                                  2.13.0
Send2Trash                              1.8.2
setproctitle                            1.3.2
setuptools                              67.7.2
shortcut                                0.0.2
simplejson                              3.19.1
sip                                     6.7.9
six                                     1.16.0
smbus                                   1.1.post2
smbus2                                  0.4.2
sortedcontainers                        2.4.0
spidev                                  3.6
stack-data                              0.6.2
systemd-python                          234
thonny                                  4.0.2
toml                                    0.10.2
tomli                                   2.0.1
tomlkit                                 0.11.8
tornado                                 6.3.1
traitlets                               5.9.0
typed-ast                               1.5.4
typing_extensions                       4.5.0
ubittool                                0.6.0
ubuntu-advantage-tools                  8001
ubuntu-drivers-common                   0.0.0
uflash                                  2.0.0
ufw                                     0.36
unattended-upgrades                     0.1
update-checker                          0.18.0
urllib3                                 2.0.2
usb-creator                             0.3.7
userpath                                1.8.0
virtualenv                              20.23.0
wadllib                                 1.3.6
wcwidth                                 0.2.6
websocket-client                        1.5.1
websockets                              11.0.3
wheel                                   0.40.0
wrapt                                   1.15.0
xkit                                    0.0.0
zipp                                    3.15.0
`

**Comment by tekktrik** [comment]
Actually, looking at your error log it doesn't actually look like it's checking PyPI but some other index, did you or your organization set it up that way?

**Comment by dsssssssss9** [comment]
organisation?
It's  just me at my dining room table i'm afraid!!

Installed circup as per instructions very  long time ago & until now the upgrade has always worked.

Just a home Ubuntu user & as far as i know nothing particular special about my setup / configuration 

not an earth shattering problem - but would love to find out what's causing it & how to solve it

**Comment by tekktrik** [comment]
It looks like it's checking `https://pypi.tuna.tsinghua.edu.cn/simple/` for packages, which isn't the typical PyPI index URL.  Do you know why it's only checking there?

**Comment by dsssssssss9** [comment]
have got 1.2.3 installed by doing  the following,,,,


edited the contents of ~/.pip/pip.conf

from 

`[global]^M
 timeout=6000 ^M
 index-url = https://pypi.tuna.tsinghua.edu.cn/simple/ ^M
 trusted-host = pypi.tuna.tsinghua.edu.cn`
 
 to
 
 `[global]
 timeout=6000
 index-url = https://pypi.python.org/simple
 trusted-host = https://pypi.python.org/      
`

uninstalled 1.2.2 as previous message

Installed via ...
`pip3 install --user circup`

1.2.3 sucessfully installs now


Have not got the faintest idea how the previous URL " https://pypi.tuna.tsinghua.edu.cn/simple" came to be the default index!!

Thank you @dhalbert  @tekktrik

**Comment by tekktrik** [comment]
Glad it's been resolved!
