### ISSUE TITLE
Does not work with Blinka

### ISSUE THREAD

**Issue by pbljung** [adafruit/circup#180]
If running on a RPI with Blinka then all circup CLI fail since it does not find circuitpython.

xxxxx@raspberrypi:~/Documents/adafruit $ circup --version
CircUp, A CircuitPython module updater. Version 1.2.4
xxxxx@raspberrypi:~/Documents/adafruit $ circup freeze
Could not find a connected CircuitPython device.
xxxxx@raspberrypi:~/Documents/adafruit $ circup list
Could not find a connected CircuitPython device.
xxxxx@raspberrypi:~/Documents/adafruit $ circup install spd31
Could not find a connected CircuitPython device.

**Comment by FoamyGuy** [comment]
Circup is made to work with microcontrollers. It does not support the Raspberry Pi or Blinka compatibility layer devices. 

You can use `pip` to install circuitpython libraries on a rasperry pi. The process is very similar to `circup`
