### ISSUE TITLE
Support for CircuitPython 9

### ISSUE THREAD

**Issue by rgov** [adafruit/circup#183]
It looks like CircuitPython 9 uses a new platform identifier `9mpy` which is not yet understood:

https://github.com/adafruit/circup/blob/abd225169a05d1e138e6e261ea76f89fb1093f8b/circup/__init__.py#L61

The bundles aren't released yet for CircuitPython 9 either.

**Comment by FoamyGuy** [comment]
@rgov In the meantime I believe you can use the `--py` flag with circup to install the python version of libraries which doesn't depend on the OS version so you can use that with devices on cutting edge versions.

i.e. 

```
circup install adafruit_requests --py
```
