### ISSUE TITLE
There was a problem downloading the bundle. Please try again in a moment

### ISSUE THREAD

**Issue by dsssssssss9** [adafruit/circup#186]
- Platform/operating system 
Ubuntu Release 20.04.6 LTS (Focal Fossa) 64-bit

- Python version 
- Python 3.8.10

- Error message you are receiving,
Downloading latest version for adafruit/CircuitPython_Community_Bundle.

There was a problem downloading the bundle. Please try again in a moment.

- List the steps to reproduce the problem below
- run any command such as "circup list"

**Comment by geoff-coppertop** [comment]
I looked at the output using --verbose and it's because there was a failure in the actions for the community bundle and no output was produced which circup is choking on when it makes its get request.

**Comment by dhalbert** [comment]
I have a PR fix for this: #184. We are also fixing the bundle building right now.

**Comment by dsssssssss9** [comment]
@geoff-coppertop 

Thank you for the information

**Comment by dsssssssss9** [comment]
@dhalbert 

as always you are on the case !

Appreciate this
