### ISSUE TITLE
Automate Version So GitHub & PyPI Always Match

### ISSUE THREAD

**Issue by sommersoft** [adafruit/circup#19]
The PyPI [version info](https://github.com/adafruit/circup/blob/master/setup.py#L63) is determined by the value of `__version__` in `circup.py`.

If this isn't updated in a PR **prior** to a release on GitHub, the PyPI deployment will simply overwrite the annotated (previous) version.

**Comment by ntoll** [comment]
@sommersoft yup :+1:

How about a script that's kicked off by `make publish-*` that checks the current version on the remote instance of PyPI and complains if the versions don't align properly (i.e. the local version MUST have a higher semver value than the current version in PyPI)..? This is not a difficult job.

**Comment by makermelissa** [comment]
I just added Github Actions in place of Travis, so perhaps that might be useful. I left the versioning manual though.

**Comment by askpatrickw** [comment]
working on this in #46

**Comment by askpatrickw** [comment]
This is fixed by PR #46
