### ISSUE TITLE
4.x bundle no longer available

### ISSUE THREAD

**Issue by tannewt** [adafruit/circup#34]
4.x bundles are no longer created. We need circup to download 5.x and 6.x now.

**Comment by cstanke** [comment]
Just ran into this myself... Any ETA on a fix?

**Comment by officialtrash** [comment]
Well! That was super fast!!! Thanks.

**Comment by cstanke** [comment]
Well! That was super fast. Thanks!!!

**Comment by mattpackwood** [comment]
@dhalbert  Any idea when the update will be available in pypi?

**Comment by dhalbert** [comment]
@mattpackwood It's on PyPi now, as 0.2.2. 0.2.1 was a correction of the version number, and should have triggered a PyPi release (which failed on 0.2.0), but for some reason the upload wasn't triggered.

**Comment by mattpackwood** [comment]
@dhalbert Thanks!  All working now!
