### ISSUE TITLE
Install dependencies

### ISSUE THREAD

**Issue by askpatrickw** [adafruit/circup#50]
When you are installing one package it may also have other dependencies called out, install those as well.

Not sure how this will work yet, but is the next thing that messes me up in my own workflow where I'm having to get one package then another package.

Not included: uninstall dependencies. Pip doesn't even do that yet.

**Comment by askpatrickw** [comment]
I was thinking that there would some way to deduce that from the library, but I see what you're pointing out.
CP libraries aren't PyPI packages so they don't follow the [package format](https://python-packaging.readthedocs.io/en/latest/dependencies.html). 

Circup is just downloading and copying files. Maybe we could include a library_name_requirements.txt file in the distributions... or maybe a longer-term support for PyPi style packages can be investigated (not required for now).

Just thoughts... ;-)

**Comment by makermelissa** [comment]
I'm not sure what the advantage of having library_name_requirements.txt would be since we already have the url for the repo and can just download the requirements.txt at the root of that.

**Comment by askpatrickw** [comment]
@makermelissa, that's a great point!
Circup won't work offline anyway so its not like grabbing a text file is that big a deal. We would need to figure out the CPython vs. CircuitPython  dependencies since Blinka, pyserial, etc. are in the requirements for many (all?) the packages.

Related: I'm taking notes on  if\how pip could be used for CPython library installs on devices over in this gist [Package Management for CircuitPython](https://gist.github.com/askpatrickw/e69eacd2c60c8e27f255d976ab5e8820)

**Comment by makermelissa** [comment]
I see. Yeah, maybe some kind of ignore list. There's only like 6 modules/packages that might be listed that are not CircuitPython related.
