### ISSUE TITLE
Make check runs pyflakes and pycodestyle, CI runs Pylint

### ISSUE THREAD

**Issue by askpatrickw** [adafruit/circup#56]
The make check is not running the same linting as the CI process.

They should be the same. Will ask on Discord about CP preferences.

**Comment by askpatrickw** [comment]
@kattni  and @tannewt  I'm not sure who should chime in on this. But if there is some preferred list of checks for the cpython code let me know. My default would be to have the checks\tests in the repo match the github action. tx!

**Comment by ladyada** [comment]
hihi folks will be back in a few days!

**Comment by kattni** [comment]
@askpatrickw Hey Patrick! I agree it should be the same. We run Pylint and Black. Sphinx builds the docs, though I'm not certain that's required for this.

**Comment by makermelissa** [comment]
I agree with @Kattni. This one is kind of the odd one out and running it on the 2 she mentioned should be good.
