### ISSUE TITLE
Handle default branch name properly

### ISSUE THREAD

**Issue by askpatrickw** [adafruit/circup#71]
The name of the default branch can change. Currently many use `master`. Many people are switching to `main`.
Ideally we can handle it being _anything_.

This affects the url used to retrieve the requirements.txt file in `libraries_from_requirements()`.

**Comment by makermelissa** [comment]
Oh, nice catch.

**Comment by askpatrickw** [comment]
@makermelissa  Yeah, I saw on discord that cater was going to change the branch on the nunchuk lib repo. So my known issue is now a problem. 🐛

**Comment by makermelissa** [comment]
Easy way would be to attempt to use main and then fall back to master, but I'm poking around to see if there's a cleaner way.

**Comment by askpatrickw** [comment]
With a get on the repo URL, we could find the URL to the requirements.txt in the reponse.
`r = requests.get("https://github.com/adafruit/circup")`

`<a class="js-navigation-open link-gray-dark" title="requirements.txt" href="/adafruit/circup/blob/master/requirements.txt">requirements.txt</a>`

and get the path to the file with regex

`href="(.+)\>requirements\.txt<\/a>`

**Comment by makermelissa** [comment]
Great solution

**Comment by askpatrickw** [comment]
I'm not fan of regex... so I kept looking...
https://docs.github.com/en/rest/reference/repos#get-a-repository

```python
url = "https://api.github.com/repos/adafruit/circup"
d = requests.get(url)
d.json()['default_branch']
'master'
```

**Comment by makermelissa** [comment]
That seems less hacky. :)

**Comment by askpatrickw** [comment]
In fixing this, I discovered two things:

1. several repos had invalid __repo__ values.
2. I wasn't checking if I got a requirments.txt back.

Not the end of the world, but I'll do a PR to fix this after the other PR is approved since that change so big.
