### ISSUE TITLE
Mu Editor Integration

### ISSUE THREAD

**Issue by makermelissa** [adafruit/circup#74]
This would be useful to add to Mu (the original author of this library was also one of the lead developers for mu). I don't believe mu supports plugins, so it would have to be added as a feature.

**Comment by ntoll** [comment]
Would love to help with this. Perhaps you could describe how you think this might work in terms of the UI..? We'd just add such a feature to the Adafruit mode..! :-)

**Comment by makermelissa** [comment]
I'm not sure. Maybe a couple buttons or a dialog?

**Comment by askpatrickw** [comment]
I'm not a Mu user, but I could see a few things, mimicking the CPI:

1. Import requirements.txt which would call circup and install libraries 
2. Freeze : show currently installed libraries 
4. Install single library
5. Upgrade device libraries
