### ISSUE TITLE
Use requirement.txt in the bundle downloads

### ISSUE THREAD

**Issue by askpatrickw** [adafruit/circup#81]
@jepler  is adding the requirements file (if one exists) to the bundle download.
https://github.com/adafruit/circuitpython-build-tools/pull/60

The requirements are within the bundle like so:
`Adafruit_CircuitPython_Bundle-6.x-mpy-20210209/requirements/adafruit_seesaw/requirements.txt`

`BUNDLE_RELEASE/requirements/LIBRARY_NAME/requirements.txt`

To remove the extra network traffic, use this instead.

**Comment by askpatrickw** [comment]
I have this blocked out... waiting for new bundles to be released with the requirements included to officially test. 
1.7.0 released 13 Feb ~ Noon so sometime after 14 Feb

**Comment by jepler** [comment]
I see you made a release of the updated circuitpython-build-tools, :tada: so now we just need to have some updated libs to release..

**Comment by askpatrickw** [comment]
Already in progress ;-)

**Comment by jepler** [comment]
whee -- https://github.com/adafruit/Adafruit_CircuitPython_Bundle/releases/tag/20210214

now we just need a community bundle update

**Comment by jepler** [comment]
I've just published a release of https://github.com/jepler/Jepler_CircuitPython_udecimal/releases/tag/1.0.2 so tomorrow's adabot run should give us an updated community bundle.

**Comment by askpatrickw** [comment]
Community bundle is an open issue, but one I'd like to add #82
