### ISSUE TITLE
Read the docs setup and Badges in README

### ISSUE THREAD

**Issue by askpatrickw** [adafruit/circup#86]
@kattni can you (or can you ask the right person) to setup read the docs for circup?

If this was a library, the url would probably be something like `https://circuitpython.readthedocs.io/projects/circup/en/latest/` but just let me know what will be and then I'll add all the badges (build, RTD, etc..) to the README.

**Comment by tannewt** [comment]
Done! https://circuitpython.readthedocs.io/projects/circup/en/latest/
